[workspace]
members = [
    "app",
    "crates/embedding",
    "crates/indexer",
    "crates/widget",
    "env",
]
resolver = "2"

[profile.release]     # shrink executable size
opt-level = "z"
lto = true
# panic = "abort"
strip = true
codegen-units = 1

[profile.dev]         # to improve productivity
opt-level = 1         # slightly optimize
lto = false           # disable link-time optimizations
incremental = false
