[package]
name = "arama"
version = "0.9.1"
edition = "2024"

description = "Image viewer and similarity calculator with offline AI power"
authors = ["nabbisen <nabbisen@scqr.net>"]
license = "Apache-2.0"

categories = ["gui"]
keywords = ["image", "walk", "filter"]
repository = "https://github.com/nabbisen/arama"
readme = "README.md"
rust-version = "1.90.0"

[dependencies]
arama-embedding = { path = "../crates/embedding" }
arama-indexer = { path = "../crates/indexer" }
arama-widget = { path = "../crates/widget" }

iced = { version = "0.14", features = ["image", "tokio"] }

anyhow = "1"
app-json-settings = "2"
rayon = "1"
serde = { version = "1", features = ["derive"] }
swdir = "0"
image = "0.25"
