[package]
name = "arama"
version = "0.8.1"
edition = "2024"

description = "Image viewer and similarity calculator with offline AI power"
authors = ["nabbisen <nabbisen@scqr.net>"]
license = "Apache-2.0"

categories = ["gui"]
keywords = ["image", "walk", "filter"]
repository = "https://github.com/nabbisen/arama"
readme = "README.md"
rust-version = "1.90.0"

[profile.release]     # shrink executable size
opt-level = "z"
lto = true
# panic = "abort"
strip = true
codegen-units = 1

[profile.dev]         # to improve productivity
opt-level = 1         # slightly optimize
lto = false           # disable link-time optimizations
incremental = false

[dependencies]
arama-embedding = { path = "../embedding" }
arama-indexer = { path = "../indexer" }
arama-widget = { path = "../widget" }

iced = { version = "0.14", features = ["image", "tokio"] }

anyhow = "1"
app-json-settings = "2"
rayon = "1"
serde = { version = "1", features = ["derive"] }
swdir = "0"
image = "0.25"
